depend: Vault
info-gui: true
actionbar-message: "&7Kazanç: &e%kazanc% &7Çarpan: &e%carpan%"
enable-worlds:
  - world
  - world_the_nether
  - world_the_end
carpan:
  vip: 20
  rehber: 10
items:
  LAPIS_BLOCK:
    sell: 1.2