name: BreakAutoSell
version: '${project.version}'
main: online.bingulhan.autosell.AutoSell
api-version: 1.18
authors: [ BingulHan ]
website: www.bingulhan.online
commands:
  asf:
    description: Fiyat listesi
  autosell:
    description: main command
  os:
    description: main command
  otosat:
    description: main command
  as:
    description: main command